- name: Install redis for Ubuntu
  when: ansible_distribution == 'Ubuntu'
  become: true
  block:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - lsb-release
          - curl
          - gpg
        state: present

    - name: Add redis gpg key
      ansible.builtin.get_url:
        url: https://packages.redis.io/gpg
        dest: /usr/share/keyrings/redis-archive-keyring.asc
        mode: '0644'

    - name: Add redis repo
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/redis-archive-keyring.asc] https://packages.redis.io/deb {{ ansible_distribution_release }} main"
        state: present

    - name: Install redis-server
      ansible.builtin.apt:
        name: redis
        state: present

    - name: Install redis
      ansible.builtin.apt:
        name: redis-tools
        state: present

- name: Install redis for CentOS or Rocky
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'
  become: true
  block:
    - name: Install redis
      ansible.builtin.dnf:
        name: redis
        state: present

- name: Start and enable redis-server
  ansible.builtin.service:
    name: redis
    state: started
    enabled: true
  become: true
