- name: Create ssh directory
  ansible.builtin.file:
    path: "/home/{{ ssh_user }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_group }}"
  become: true

- name: Copy ssh_config
  ansible.builtin.copy:
    src: files/config
    dest: "/home/{{ ssh_user }}/.ssh/config"
    mode: "0600"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_group }}"
  become: true

- name: Create deploy key
  community.crypto.openssh_keypair:
    path: "/home/{{ ssh_user }}/.ssh/id_ed25519"
    type: ed25519
  become: true
  become_user: "{{ ssh_user }}"
  register: deploy_key

- name: Print deploy key
  ansible.builtin.debug:
    msg: "{{ deploy_key.public_key }}"
