- name: Create ssh directory
  file:
    path: "/home/{{ ssh_user }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_group }}"
  become: true
  become_user: isucon

- name: Copy ssh key
  copy:
    src: "{{ item }}"
    dest: "/home/{{ ssh_user }}/.ssh/"
    mode: "0600"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_group }}"
  with_fileglob:
    - "files/id_ed25519*"
  become: true
  become_user: "{{ ssh_user }}"

# - name: Copy authorized_keys
#   copy:
#     src: files/authorized_keys
#     dest: "/home/{{ ssh_user }}/.ssh/authorized_keys"
#     mode: "0600"
#     owner: "{{ ssh_user }}"
#     group: "{{ ssh_group }}"
#   become: true
#   become_user: "{{ ssh_user }}"

- name: Copy ssh_config
  copy:
    src: files/config
    dest: "/home/{{ ssh_user }}/.ssh/config"
    mode: "0600"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_group }}"
  become: true
  become_user: "{{ ssh_user }}"
