- name: Copy util files
  ansible.builtin.copy:
    src: files/
    dest: "{{ webapp_dir }}"
    mode: "0755"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_group }}"
  become: true

- name: Run initialize
  community.general.make:
    target: initialize
    chdir: "{{ webapp_dir }}"
