- name: install unzip
  package:
    name: zip
    state: present
  become: true

- name: Install alp
  unarchive:
    src: https://github.com/tkuchiki/alp/releases/download/v1.0.12/alp_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: yes
  become: true
