- name: Create mysql log directory
  ansible.builtin.file:
    path: /var/log/mysql
    state: directory
    owner: mysql
    group: mysql
    mode: "755"
  become: true

- name: Create slow log file
  ansible.builtin.file:
    path: /var/log/mysql/mysql-slow.log
    state: touch
    owner: mysql
    group: mysql
    mode: "0644"
  become: true

- name: Copy configs (Ubuntu)
  ansible.builtin.copy:
    src: files/
    dest: /etc/mysql/mysql.conf.d/
    mode: "0644"
    owner: root
    group: root
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Restart mysql (Ubuntu)
  ansible.builtin.service:
    name: mysql
    state: restarted
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Copy configs (Rocky)
  ansible.builtin.copy:
    src: files/
    dest: /etc/my.cnf.d/
    mode: "0644"
    owner: root
    group: root
  become: true
  when: ansible_distribution == 'Rocky'

- name: Restart mysql (Rocky)
  ansible.builtin.service:
    name: mysqld
    state: restarted
  become: true
  when: ansible_distribution == 'Rocky'
