- name: Create mysql log directory
  ansible.builtin.file:
    path: /var/log/mysql
    state: directory
    owner: mysql
    group: mysql
    mode: "755"
  become: true

- name: Create slow log file
  ansible.builtin.file:
    path: /var/log/mysql/mysql-slow.log
    state: touch
    owner: mysql
    group: mysql
    mode: "0644"
  become: true

- name: Copy slow log conf
  ansible.builtin.copy:
    src: files/slow_log.cnf
    dest: /etc/mysql/mysql.conf.d/
    mode: "0644"
    owner: root
    group: root
  become: true

- name: Restart mysql
  ansible.builtin.service:
    name: mysql
    state: restarted
  become: true
