- name: Create ssh directory
  ansible.builtin.file:
    path: "/home/{{ ssh_user }}/.ssh"
    state: directory
    mode: "0700"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_group }}"
  become: true

- name: Copy authorized_keys
  ansible.builtin.copy:
    src: files/authorized_keys
    dest: "/home/{{ ssh_user }}/.ssh/authorized_keys"
    mode: "0600"
    owner: "{{ ssh_user }}"
    group: "{{ ssh_group }}"
  become: true
