- name: Install pt-query-digest
  apt:
    name: percona-toolkit
    state: present
  become: true

- name: Create slow log file
  file:
    path: /var/log/mysql/mysql-slow.log
    state: touch
    owner: mysql
    group: mysql
    mode: "0644"
  become: true
