- name: Install pt-query-digest (ubuntu)
  ansible.builtin.apt:
    name: percona-toolkit
    state: present
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install percona repository (centos or rocky)
  ansible.builtin.yum:
    name: https://repo.percona.com/yum/percona-release-latest.noarch.rpm
    state: present
    disable_gpg_check: true
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'

- name: Install pt-query-digest (centos or rocky)
  ansible.builtin.yum:
    name: percona-toolkit
    state: present
  become: true
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky'
