- name: Install unzip
  ansible.builtin.package:
    name: zip
    state: present
  become: true

- name: Install pprotein
  ansible.builtin.unarchive:
    src: https://github.com/youdofoo/pprotein/releases/download/v1.2.4-youdofoo/pprotein_1.2.4-youdofoo_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true
  become: true

# pprotein は isu1 でのみ有効化
- name: Create pprotein data directory
  ansible.builtin.file:
    path: /opt/pprotein/data
    state: directory
    mode: '0755'
  become: true
  when: inventory_hostname == 'isu1'

- name: Place pprotein service file
  ansible.builtin.copy:
    src: files/pprotein.service
    dest: /etc/systemd/system/pprotein.service
    mode: '0644'
    owner: root
    group: root
  become: true
  when: inventory_hostname == 'isu1'

- name: Copy setting files
  ansible.builtin.copy:
    src: files/settings/
    dest: /opt/pprotein/data/
    mode: '0666'
    owner: root
    group: root
  become: true
  when: inventory_hostname == 'isu1'

- name: Start pprotein
  ansible.builtin.service:
    name: pprotein
    state: started
    enabled: true
  become: true
  when: inventory_hostname == 'isu1'

# pprotein-agent は全ホストで有効化
- name: Place pprotein-agent service file
  ansible.builtin.copy:
    src: files/pprotein-agent.service
    dest: /etc/systemd/system/pprotein-agent.service
    mode: '0644'
    owner: root
    group: root
  become: true

- name: Start pprotein-agent
  ansible.builtin.service:
    name: pprotein-agent
    state: started
    enabled: true
  become: true
  when: inventory_hostname == 'isu1'
