- name: Install unzip
  ansible.builtin.package:
    name: zip
    state: present
  become: true

- name: Install pprotein
  ansible.builtin.unarchive:
    src: https://github.com/kaz/pprotein/releases/download/v1.2.3/pprotein_1.2.3_linux_amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true
  become: true

- name: Create pprotein data directory
  ansible.builtin.file:
    path: /opt/pprotein/data
    state: directory
    mode: '0755'
  become: true

- name: Place pprotein service file
  ansible.builtin.copy:
    src: files/pprotein.service
    dest: /etc/systemd/system/pprotein.service
    mode: '0644'
    owner: root
    group: root
  become: true

- name: Place pprotein-agent service file
  ansible.builtin.copy:
    src: files/pprotein-agent.service
    dest: /etc/systemd/system/pprotein-agent.service
    mode: '0644'
    owner: root
    group: root
  become: true

- name: Copy setting files
  ansible.builtin.copy:
    src: files/settings/
    dest: /opt/pprotein/data/
    mode: '0666'
    owner: root
    group: root
  become: true
