{
 "title": "ISUCON",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1s",
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(host)" } }
  ]
 },
 "panels": [
  {
   "title": "${host}",
   "type": "canvas",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "repeat": "host",
   "targets": [
    {
     "expr": "count by () (node_cpu_seconds_total{host=\"$host\",mode=\"user\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "node_memory_MemTotal_bytes{host=\"$host\"}/1024/1024/1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 2 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum by(mode) (rate(node_cpu_seconds_total{mode=~\"user|system\", host=\"$host\"}[$__rate_interval])) * 100) / scalar(count by() (node_cpu_seconds_total{mode=\"user\", host=\"$host\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU使用率Top5",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(topk(5, sum by(groupname) (rate(namedprocess_namegroup_cpu_seconds_total{host=\"$host\"}[$__rate_interval]))) * 100) / scalar(count by() (node_cpu_seconds_total{mode=\"user\",host=\"$host\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "メモリ使用率",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 12 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(1 - node_memory_MemAvailable_bytes{host=\"$host\"} / node_memory_MemTotal_bytes{host=\"$host\"}) * 100",
     "legendFormat": "%memory"
    }
   ]
  },
  {
   "title": "ディスクI/O",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 16 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{device}} Read"
    },
    {
     "expr": "-rate(node_disk_written_bytes_total{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{device}} Write"
    }
   ]
  },
  {
   "title": "ネットワークI/O",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 20 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{device}} Rx"
    },
    {
     "expr": "-rate(node_network_transmit_bytes_total{host=\"$host\"}[$__rate_interval])",
     "legendFormat": "{{device}} Tx"
    }
   ]
  }
 ]
}