- name: Install git (ubuntu)
  ansible.builtin.apt:
    name: git
    state: present
  become: true
  when: ansible_distribution == 'Ubuntu'

- name: Install ius repository (centos)
  ansible.builtin.yum:
    name:
      - https://repo.ius.io/ius-release-el7.rpm
      - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
    state: present
  become: true
  when: ansible_distribution == 'CentOS'

- name: Install git (centos)
  ansible.builtin.yum:
    name: git
    enablerepo: ius
    state: present
  become: true
  when: ansible_distribution == 'CentOS'

- name: Install git (rocky)
  ansible.builtin.yum:
    name: git
    state: present
  become: true
  when: ansible_distribution == 'Rocky'

- name: Configure git user.email
  community.general.git_config:
    name: user.email
    scope: global
    value: "{{ git_user }}@example.com"
  become: true
  become_user: "{{ git_user }}"

- name: Configure git user.name
  community.general.git_config:
    name: user.name
    scope: global
    value: "{{ git_user }}"
  become: true
  become_user: "{{ git_user }}"

- name: Init git on webapp dir
  ansible.builtin.command:
    cmd: git init
    chdir: "{{ webapp_dir }}"
  become: true
  become_user: "{{ git_user }}"
  register: git_init
  changed_when: git_init.rc == 0

- name: Change default branch name
  ansible.builtin.command:
    cmd: git branch -M main
    chdir: "{{ webapp_dir }}"
  become: true
  become_user: "{{ git_user }}"
  register: git_branch
  changed_when: git_branch.rc == 0

- name: Set remote repository
  ansible.builtin.command:
    cmd: "git remote add origin git@github.com:{{ github_repo }}.git"
    chdir: "{{ webapp_dir }}"
  become: true
  become_user: "{{ git_user }}"
  register: git_remote
  changed_when: git_remote.rc == 0
  failed_when: git_remote.rc != 0 and 'remote origin already exists' not in git_remote.stderr
