- name: Install git
  apt:
    name: git
    state: present
  become: true

- name: Configure git user.email
  git_config:
    name: user.email
    scope: global
    value: isucon@example.com
  become: true
  become_user: isucon

- name: Configure git user.name
  git_config:
    name: user.name
    scope: global
    value: isucon
  become: true
  become_user: isucon
