- name: Comment out default access log conf
  ansible.builtin.lineinfile:
    path: /etc/nginx/nginx.conf
    regexp: '^(\s+access_log .*)'
    backrefs: true
    line: '#\1'
  become: true

- name: Copy access log conf
  ansible.builtin.copy:
    src: files/access_log.conf
    dest: /etc/nginx/conf.d/
    mode: "0644"
    owner: root
    group: root
  become: true

- name: Check if access log exists
  ansible.builtin.stat:
    path: /var/log/nginx/access.log
  register: access_log_stat

- name: Add read permission to access log
  ansible.builtin.file:
    path: /var/log/nginx/access.log
    mode: "0644"
  become: true
  when: access_log_stat.stat.exists

- name: Restart nginx
  ansible.builtin.systemd_service:
    name: nginx
    state: restarted
  become: true
