---
- name: Main
  hosts: webservers
  remote_user: root
  roles:
    - hostname
    - utils
    - apt
    - alp
    - pt-query-digest
    - ssh
    - git
    - nginx
    - mysql
    - redis
    # - graphviz
