- name: disable auto-upgrades
  copy:
    src: files/20auto-upgrades
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: "0644"
    owner: root
    group: root
  become: true
  register: auto_upgrades
  when: ansible_distribution == 'Ubuntu'

- name: apt update
  apt:
    update_cache: true
  become: true
  when: ansible_distribution == 'Ubuntu'
